[project]
[tool.uv.required-environments]
linux_x86_64 = true
name = "uv-cloudflare-workers-example"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cffi",
    "fastapi",
    "jinja2",
]
