name = "uv-worker"
main = "worker.js"
compatibility_date = "2025-12-07"
# Optional: Enable HTMLRewriter streams for performance
compatibility_flags = ["nodejs_compat"]


[observability.logs]
enabled = true

[[rules]]
globs = ["vendor/**"]
type = "Data"
fallthrough = true
